
Jonnitto:
  MultiColumn:
    rowClass: row
    Media:
      defaultMode: height
      baseWidth: 1440
      class:
        containerFluid: false
        row: jonnitto-multicolumn-media--row
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.MultiColumn:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.MultiColumn: true
