Jonnitto:
  ImagesInARow:
    baseWidth: 1440
    class:
      containerFluid: false
      row: jonnitto-imagesinarow-media--row

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.ImagesInARow:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.ImagesInARow: true
