TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.MultiColumn': TRUE

    userInterface:
      translation:
        autoInclude:
          'Jonnitto.MultiColumn': ['NodeTypes/*']

Jonnitto:
  MultiColumn:
    rowClass: row
