Jonnitto:
  MultiColumn:
    container: false
    row: row

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.MultiColumn:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.MultiColumn: true
